### ISSUE TITLE
Set a static range for the flow intensities.

### ISSUE THREAD

**Issue by TLDuhamel** [FlowmapBlue/flowmap.blue#24]
Often when panning around the map, or selecting different points, the automatic re-scaling of the flows makes comparisons difficult.

For example when selecting one node, the thickest flows might represent 400 trips, but when selecting another node, the thickest flow might only represent 25 trips. This behaviour is understandable and sensible when comparing flows to/from a specific node, but can make it confusing to compare flows when regularly isolating different nodes.

It could be useful to toggle this auto-scaling, perhaps also with an input (slider or text-box) to manually set the range.

**Comment by ilyabo** [comment]
That's a fair point. I think adding a toggle for auto-scaling would be a reasonable solution.

**Comment by ilyabo** [comment]
I added this switch:
<img src=https://user-images.githubusercontent.com/351828/89228315-ade34f00-d5df-11ea-9b82-c998a72159a8.png width=200>
