### ISSUE TITLE
Module not found: Can't resolve '@flowmap.blue/core'

### ISSUE THREAD

**Issue by PetengDedet** [FlowmapBlue/flowmap.blue#27]
Cloning repo, run `yarn install`, then `npm start` getting error
```
./src/index.tsx
Module not found: Can't resolve '@flowmap.blue/core' in '/Users/mac/flowmap.blue/packages/app/src'
```

- OS: MacOS Catalina
- Node: v12.10.0
- NPM: 6.11.3
- Yarn: 1.17.3

**Comment by ilyabo** [comment]
The project uses [yarn workspaces](https://classic.yarnpkg.com/en/docs/workspaces/). The core module needs to be built from the source too. Try `yarn dev` in the root directory if you want to run it locally.

**Comment by PetengDedet** [comment]
Usually i use npm for my daily dev. 
Trying `yarn dev` and it works now.

Thanks @ilyabo

**Comment by ilyabo** [comment]
`npm run dev` should also work

**Comment by PetengDedet** [comment]
Yes, it is. Thank you 👏
