### ISSUE TITLE
Example points to 0,0 location

### ISSUE THREAD

**Issue by guillermodangelo** [FlowmapBlue/flowmap.blue#40]
The example Google Sheet generates a point at 0,0 and points flows to there.

**Comment by ilyabo** [comment]
Hi Guillermo!
Do you mean the template spreadsheet? Could you share a screenshoot? I cannot reproduce the issue.

**Comment by guillermodangelo** [comment]
Sure. It's very weird. It only happens on Firefox in Ubuntu (not in Ubuntu Chrome nor Widows Chrome or Firefox).
It happens with any map, nor just the template.

![Captura de pantalla de 2021-09-22 10-20-39](https://user-images.githubusercontent.com/19522568/134351571-225882c5-14fa-4186-84aa-31dafa2f1e49.png)

**Comment by ilyabo** [comment]
Hi @guillermodangelo! I just upgraded deck.gl in the app. Could you please recheck if the issue still persists on Ubuntu?

**Comment by guillermodangelo** [comment]
Fixed! Thank you.

**Comment by ilyabo** [comment]
Great, thanks!
