### ISSUE TITLE
Does not work in Safari any more

### ISSUE THREAD

**Issue by mountainMath** [FlowmapBlue/flowmap.blue#47]
I have run into the same issues in other apps and updating deck.gl to a newer version fixed this for me. Might be as easy as bumping the version number, but could require some other tweaks too to adapt to new deck.gl version.

**Comment by ilyabo** [comment]
Just tried it in Safari, seems to work:
![image](https://user-images.githubusercontent.com/351828/142586176-f87d8162-667f-47c7-b375-362dd052fe78.png)
Could you pls share more details on how to reproduce?

**Comment by mountainMath** [comment]
I am getting WebGL errors for [this map](https://flowmap.blue/13Q-xsfL59XXPw7-3ue_9G9xab9FtYiL3S9vOZp-yJyY?v=49.175607%2C-122.438242%2C8.65%2C0%2C0&a=1&as=1&b=1&bo=75&c=1&ca=1&d=1&fe=1&lt=1&lfm=ALL&col=Default&f=50).
<img width="392" alt="image" src="https://user-images.githubusercontent.com/1395960/142658053-5c2ed9ce-a9b3-43c0-9bd5-3718d89b66bb.png">

Safari 15.1 on a MacBook Pro running macOS 12.0.1. Runs fine in Chrome. I have had the same problem with other deck.gl maps, I fixed it [for one of them](https://mountainmath.ca/ns_cap) by updating the deck.gl version and still need to fix it for [this one that right now is still broken with the same error](https://mountainmath.ca/cov_zoning_history).

**Comment by ilyabo** [comment]
Still couldn't reproduce it on neither of my two Macs, will try again once I upgrade to MacOS 12

**Comment by LeLunZ** [comment]
That's how it is for me: [Screen Shot 2021-11-25 at 14 29 08](https://user-images.githubusercontent.com/31982496/143451260-fb237e5d-5713-43bd-a953-ffac655e1928.png)

The Warning popup is not always there. On the first example (migration in Switzerland 2016) its missing, on the second example (South East Queensland Public Transport Network) its showing the warning for the locations.

**Comment by LeLunZ** [comment]
I also tested these (didn't work on all of them) on iOS 15.1.1:
- Chrome iOS
- Firefox iOS 
- Edge iOS 

So it could be that its not working on more/all iOS Browsers.

*Copied from above*
**The Warning popup is not always there. On the first example (migration in Switzerland 2016) its missing, on the second example (South East Queensland Public Transport Network) its showing the warning for the locations.  **

Here some pictures:
## Firefox
![IMG_0313](https://user-images.githubusercontent.com/31982496/143452384-8d659ab6-f204-463f-8172-613376d36fd9.PNG)

## Safari
![IMG_0314](https://user-images.githubusercontent.com/31982496/143452489-9aaa6596-f023-4782-a3a9-d47bbb9e9ffa.PNG)

## Chrome
![IMG_0315](https://user-images.githubusercontent.com/31982496/143452627-fe4c83a3-614e-4bf2-ab1a-fe48c3bce7e4.PNG)

## Edge
![IMG_0321](https://user-images.githubusercontent.com/31982496/143453070-1a2b7759-1415-4df8-8716-de22441060d6.PNG)

## Chrome without location warning
![IMG_0316](https://user-images.githubusercontent.com/31982496/143452880-0e9a2887-9037-4f72-8abd-7d614fcb06ad.PNG)

## Firefox without location warning
![IMG_0317](https://user-images.githubusercontent.com/31982496/143452921-c869cc5b-ac32-4ecf-8fb5-2a518ffa0581.PNG)

## Safari without location warning
![IMG_0318](https://user-images.githubusercontent.com/31982496/143452976-e82f649b-fc3d-469b-bbb0-2e833fdc5565.PNG)

**Comment by ilyabo** [comment]
Okay, I could reproduce it now. Will try to upgrade deck.gl and see if it solves the issue. Thanks for letting me know!

**Comment by LeLunZ** [comment]
@ilyabo it seems also the examples on flowmap.gl in the [storybook](https://teralytics.github.io/flowmap.gl/index.html?path=/story/basic--basic-as-layer) are broken.

**Comment by ilyabo** [comment]
Looks like it should be working now. @LeLunZ  Can you confirm?

**Comment by LeLunZ** [comment]
It is! 👍

**Comment by ilyabo** [comment]
Cool, thanks again!

**Comment by mountainMath** [comment]
Thanks everyone, works perfectly now!
